name: 'Setup Massdriver CLI'
description: 'Sets up the Massdriver CLI'
author: 'Massdriver, Inc.'
inputs:
  version:
    description: 'The release version to fetch. Example: v0.4.8.'
    required: false
    default: 'latest'
  token:
    description: 'The GitHub token. Typically this will be secrets.GITHUB_TOKEN'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
