name: 'Massdriver'
description: |
  Set up the Massdriver CLI.
author: 'Massdriver, Inc.'
inputs:
  tag:
    description: |
      The release tag to fetch. Can be either a tag like `1.0.0` or `latest`.
      Releases can be found at https://github.com/massdriver-cloud/mass.
    required: false
    default: 'latest'
  token:
    description: |
      The GitHub token used to fetch a release. This is set by GitHub Actions.'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/setup/index.js'
