name: Massdriver Deploy
on:
  push:
    branches: [main]

# Fill in empty values before use and set secrets in GitHub
env:
  # Massdriver Secrets
  MASSDRIVER_API_KEY: ${{secrets.MASSDRIVER_API_KEY}}
  MASSDRIVER_ORG_ID: ${{secrets.MASSDRIVER_ORG_ID}}
  MASSDRIVER_ARTIFACT_ID: ${{secrets.MASSDRIVER_ARTIFACT_ID}}
  # Package Variables
  MASSDRIVER_PROJECT:
  MASSDRIVER_ENVIRONMENT:
  MASSDRIVER_MANIFEST:
  # Registry Variables
  REGISTRY_NAMESPACE:
  REGISTRY_IMAGE_NAME:
  REGISTRY_REGION:
  # Local paths
  BUNDLE_FOLDER: ./bundle
  # Image Tag
  IMAGE_TAG: ${{github.sha}}

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yaml
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v3
      - name: Install Massdriver CLI
        uses: massdriver-cloud/actions/setup@v4
      - name: Push Image
        uses: massdriver-cloud/actions/image_push@v4
        with:
          namespace: ${{env.REGISTRY_NAMESPACE}}
          image-name: ${{env.REGISTRY_IMAGE_NAME}}
          region: ${{env.REGISTRY_REGION}}
          artifact: ${{env.MASSDRIVER_ARTIFACT_ID}}
          image-tag: ${{env.IMAGE_TAG}}
      - name: Publish Bundle
        uses: massdriver-cloud/actions/bundle_publish@v4
        with:
          build-directory: ${{env.BUNDLE_FOLDER}}
      - name: Set Image Tag
        uses: massdriver-cloud/actions/app_patch@v4
        with:
          project: ${{env.MASSDRIVER_PROJECT}}
          env: ${{env.MASSDRIVER_ENVIRONMENT}}
          manifest: ${{env.MASSDRIVER_MANIFEST}}
          set: |
            .image.tag = "${{env.IMAGE_TAG}}"
      - name: Deploy
        uses: massdriver-cloud/actions/app_deploy@v4
        with:
          project: ${{env.MASSDRIVER_PROJECT}}
          env: ${{env.MASSDRIVER_ENVIRONMENT}}
          manifest: ${{env.MASSDRIVER_MANIFEST}}
