name: 'Preview Decommission'
description: 'Decommission a Massdriver Preview Environment'
author: 'Massdriver, Inc.'
inputs:
  params:
    description: 'Path to the preview params JSON file'
    required: false
    default: './preview.json'
runs:
  using: node20
  main: '../dist/preview_decommission/index.js'
