name: 'Setup Massdriver CLI'
description: 'Sets up the Massdriver CLI'
author: 'Massdriver, Inc.'
inputs:
  tag:
    description: |
      The release tag to fetch. Can be either a tag like `v0.4.8` or `latest`.
      Releases can be found at https://github.com/massdriver-cloud/massdriver-cli.
    required: false
    default: 'latest'
  token:
    description: |
      The GitHub token used to fetch a release. This is set by GitHub Actions.'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: '../dist/index.js'
